# Header
menu:
  主页: /
  博文: /archives

# Content
excerpt_link: 更多
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
 - category
 - tagcloud
 - archive

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics:
favicon: /css/images/logo.jpg
twitter: https://twitter.com/bevis_shen
fb_admins: https://www.facebook.com/bevis1991
